// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/6/2026, 10:43:46 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/USER/aaron-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/aaron-portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/aaron-portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/aaron-portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/aaron-portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/USER/aaron-portfolio/composables/**/*.{js,ts,mjs}","C:/Users/USER/aaron-portfolio/utils/**/*.{js,ts,mjs}","C:/Users/USER/aaron-portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/aaron-portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/aaron-portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/aaron-portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;